all:
	cargo run -- --ant 8 --samples 1000 --fname test_vectors_1000_8ant_1bit.txt

# The file consists of IQIQIQIQIQ for each of the specified number of antennas.
two:
	cargo run -- --ant 8 --samples 1000 --bits 2 --fname test_vectors_1000_8ant_2bit.txt
	
